### PR TITLE
Added the files to correct folders

### PR DESCRIPTION
**Pull request by Niyati3031**
i have made necessary changes, please check and let me know if i need to change anything else as well, thanks for assigning this to me..

### CODE REVIEW

**Comment by Saicharan67** [comment]
Hey that's an awesome work

**Review by Saicharan67 — CHANGES_REQUESTED** [review]
Revert back your changes for this file

**Comment by Niyati3031** [comment]
> Revert back your changes for this file

sorry to say but can you mention the file i am not able to figure out which file are talking about

**Comment by Saicharan67** [comment]
Dp on trees problem

**Comment by Niyati3031** [comment]
> Dp on trees problem

diameter of trees?

**Comment by Saicharan67** [comment]
yep

**Comment by Niyati3031** [comment]
check now

**Comment by Niyati3031** [comment]
@Saicharan67 is this pr hacktoberfest accepted

**Comment by Saicharan67** [comment]
Please check it over here
https://hacktoberfest.digitalocean.com/profile

**Comment by Niyati3031** [comment]
@Saicharan67 can you please add hacktoberfest accepted tag to my pr it would be very helpful as its my first time contributing...

**Pull request merged**
