### PR TITLE
sort problem

### PR DESCRIPTION
**Pull request by HarnishSavsani**
was asked in adobe 2020

### CODE REVIEW

**Comment by Saicharan67** [comment]
Hey, @HarnishSavsani This repo contains High Standard Interview questions Only. Try to come up with somewhat difficult problems

**Comment by HarnishSavsani** [comment]
Actually this problem was like salt, looks small but imagine food without salt . Similarly this problem was asked many time in Adobe.

**Comment by Saicharan67** [comment]
Yeah I got You😇

**Comment by HarnishSavsani** [comment]
arent we participated in hacktoberfest ?

**Pull request merged**
